"""
Configuration for OptiFlow
"""

# ---GRID SETTINGS---
GRID_ROWS = 3
GRID_COLS = 3

# ---SIMULATION SETTING---
SIM_STEPS = 100
VEHICLE_SPAWN_RATE = 0.3

# ---ROAD SETTINGS---
ROAD_LENGTH = 5
LANE_CAPACITY = 10

# ---TRAFFIC LIGHT SETTINGS---
GREEN_DURATION = 5
YELLOW_DURATION = 1
NUM_PHASES = 2

# ---VEHICLE SETTINGS---
VEHICLE_SPEED = 1

# ---RL SETTINGS---
ALPHA = 0.1
GAMMA = 0.95

EPSILON_START = 1.0
EPSILON_MIN = 0.05
EPSILON_DECAY = 0.99
TRAIN_EPISODES = 100
