"""
Configuration for OptiFlow
"""

# ---GRID SETTINGS---
GRID_ROWS = 1
GRID_COLS = 2

# ---SIMULATION SETTING---
SIM_STEPS = 50
VEHICLE_SPAWN_RATE = 0.3

# ---ROAD SETTINGS---
ROAD_LENGTH = 5
LANE_CAPACITY = 10

# ---TRAFFIC LIGHT SETTINGS---
GREEN_DURATION = 5
YELLOW_DURATION = 1
NUM_PHASES = 2

# ---VEHICLE SETTINGS---
VEHICLE_SPEED = 1